### ISSUE TITLE
Should be save the original master.mdb in source code and keep up-to-dated

### ISSUE THREAD

**Issue by Kotoki1337** [FabulousCupcake/umamusume-db-translate#11]
replacing the stings of the database is done via the Japanese string. If I have completed a replacement and i may not have saved the original database. Then I will lose the original database and will not be able to use the web page to replace the new translation, cuz the replacement is based on Japanese.

**Comment by FabulousCupcake** [comment]
I'm not sure I understand your question, but I'll try anyways:

> Should you keep the original untranslated master.mdb file?

Not really, if you need a fresh copy then simply delete it and launch the game. It will download fresh unmodified one.  
You can keep a backup, but it's easy to redownload it again too, so no big risk for not having a backup copy.

  

> Can you pass the translated mdb file through the patcher again if it has new translations?

Sure, but it will only replace exact matches of the japanese string, so it will only work for newly translated texts, and not already-translated texts.

**Comment by Kotoki1337** [comment]
I am sorry that I did not describe it clearly.

> Can you pass the translated mdb file through the patcher again if it has new translations?

What I mean is that in a translation environment I may need to change the translated text several times and after I have changed it once, the string in the database has been changed to the translated text so I can apply again, but I have a solution for that like u said in #13 

> Should you keep the original untranslated master.mdb file?

I mean u guys can create a backup folder or release which include the latest .mdb file or some important stuff here like my [repo](https://github.com/HorizonKinen/umamusume-db-translate-zh/tree/main/backup)

**Comment by FabulousCupcake** [comment]
`git` is not suitable for keeping binary files/blobs, hence why it's not stored in this repo; it would balloon up to hundreds of megabytes very quickly in about a year.  
Though my main reason would be sketchy copyright concerns; you can keep personal backup of past mdb files, but it will not be put in this repo.

Re: double-translation bug, let's keep the discussion in #13.
