### ISSUE TITLE
`help.csv` not displayed correctly

### ISSUE THREAD

**Issue by FabulousCupcake** [FabulousCupcake/umamusume-db-translate#87]
This issue is split from https://github.com/FabulousCupcake/umamusume-db-translate/pull/86, which introduced the translation on [`help.csv`](https://github.com/FabulousCupcake/umamusume-db-translate/blob/master/src/data/help.csv) file.

Unfortunately some translations are too long and gets cut off:  
![https://user-images.githubusercontent.com/7202881/131828728-9eed85c0-5b34-4348-91ff-2a9604e49560.png](https://user-images.githubusercontent.com/7202881/131828728-9eed85c0-5b34-4348-91ff-2a9604e49560.png)

In other worse cases, it gets cut-off on a markup closing tag (e.g. `</size>`) and it fails to render all the markup, making the text barely legible.

**Comment by noccu** [comment]
Ah dang, I was working on this today and just pushed [the update](https://github.com/noccu/umamusume-db-translate/commit/c7f40c658d9fc6337a0a295ce46e601dbabd08a6), hah.

**Comment by FabulousCupcake** [comment]
Cool! You should be able to rebase and open another PR 😄
