### ISSUE TITLE
Text color not rendered

### ISSUE THREAD

**Issue by latoulicious** [FabulousCupcake/umamusume-db-translate#94]
Anyone know what causes this color not rendered? they all have the **closing tag** but it wont rendered correctly or it is a problem from my own machine?

![unknown_2](https://user-images.githubusercontent.com/45010096/134453053-3eedd3ce-ec69-484c-870c-d1bdbe68485e.png)

**Comment by noccu** [comment]
Should be fixed now that 865b4f3d7fbc37bb10e17b737e345b8d3f5831d9 is merged in.
Let me know if there are still issues on the latest version.
